name: Vita Prepare for Pull Request

on:
  push:
    paths:
    - ".github/control/prepareForPullRequest.txt"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Download repository
      uses: actions/checkout@v2

    - name: Install software packages
      run: |
        export PERL_MM_USE_DEFAULT=1
        sudo cpan install JSON Data::Table::Text GitHub::Crud Data::Dump 1>/dev/null


    - name: Delete and refresh generated files so they match in a pull request
      env:
         token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        perl github/deleteGeneratedFiles.pl $GITHUB_REPOSITORY $token
